export {
  clickPoint,
  clickRect,
  clickRectWithoutSync,
  dragBetweenPoints,
  dragRectToRect,
  keyAction,
  movePoint,
  pointerButton,
  pointerWheel,
  rightClickPoint,
  rightClickRect,
  tapKey,
  typeText,
} from './runtime.ts'
