export {
  clickPoint,
  clickRect,
  clickRectWithoutSync,
  dragBetweenPoints,
  dragRectToRect,
  keyAction,
  movePoint,
  pointerButton,
  pointerWheel,
  rightClickPoint,
  rightClickRect,
  tapKey,
  touchCancel,
  touchDown,
  touchMove,
  touchSequence,
  touchTap,
  touchUp,
  typeText,
} from './runtime.ts'
